questions = [
    ["A set of instructions that tells the computer how to behave, what to do and derive at a solution to a particular problem is\n a) Algorithm\n b) Pseudocode\n c) Programming\n d) Program\n","d"],   
    ["What is a Functional Requirement?\n a) specifies the tasks the program must complete\n b) specifies the tasks the program should not complete\n c) specifies the tasks the program must not work\n d) All of the mentioned\n","a"],
    ["A set of logical sequenced instructions that allows to find the solution to a problem is:\n a) Algorithm\n b) Pseudocode\n c) Programming\n d) Program\n","a"],
    ["The activity that distributes estimated effort across the planned project duration by allocating the effort to specific software developing tasks is ____________\n a) Project scheduling\n b) Detailed schedule\n c) Macroscopic schedule\n d) None of the mentioned\n","a"],
    ["_____ is defined as the process of generating analysis and designing documents?\n a) Re-engineering\n b) Reverse engineering\n c) Software re-engineering\n d) Science and engineering\n","b"],
    ["The six stages of program development in a logical order are:\n a) Define, Analyze, Write, Test, Document, Debug\n b) Define, Analyze, Develop, Write, Test and Debug, Document\n c) Define, Write, Develop, Analyze, Test, Document\n d) Define, Develop, Write, Test, Document, Debug\n","b"],
    ["CASE stands for\n a) Computer-Aided Software Engineering\n b) Control Aided Science and Engineering\n c) Cost Aided System Experiments\n d) None of the mentioned\n","a"],
    ["An erroneous system state that results in an unexpected system behavior is acknowledged as?\n a) System failure\n b) Human error or mistake\n c) System error\n d) System fault\n","c"],
    ["Define Agile scrum methodology.\n a) project management that emphasizes incremental progress\n b) project management that emphasizes decremental progress\n c) project management that emphasizes neutral progress\n d) project management that emphasizes no progress\n","a"],
    ["Which of the following refers to internal software equality?\n a) Scalability\n b) Reusability\n c) Reliability\n d) Usability\n","b"],
    ["_____ is a software development activity that is not a part of software processes.\n a) Validation\n b) Specification\n c) Development\n d) Dependence\n","d"],
    ["The first phase of software development is\n a) Coding\n b) Testing \n c) Design \n d) Requirement analysis\n","d"],
    ["What are the features of Software Code?\n a) Simplicity\n b) Accessibility\n c) Modularity\n d) All of the above\n","c"],
    ["Who is the father of Software Engineering?\n a) Margaret Hamilton\n b) Watts S. Humphrey\n c) Alan Turing\n d) Boris Beizer\n","b"],
    ["A computer program can often be a very satisfactory _____ of a physical system such as road traffic conditions.\n a) Solution\n b) Replacement\n c) Model\n d) Simulation\n","d"],
    ["What is Software Engineering? \n a) Designing a software\n b) Testing a software\n c) Application of engineering principles to the design a software\n d) None of the above\n","c"],
    ["The model which reduces the cost of development of software is\n a) Waterfall model\n b) Iterative\n c) Prototyping\n d) None of these\n","c"],
    ["Software is defined as __\na) set of programs, documentation & configuration of data\nb) set of programs\nc) documentation and configuration of data\nd) None of the mentioned\n","a"],
    ["The maximum efforts distribution in phases of software development is\n a) Coding\n b) Testing\n c) Design phase\n d) Requirement analysis\n","b"],
    ["The recent model is\n a) Waterfall model\n b) Prototyping\n c) Spiral\n d) Iterative\n","c"],
    ["Regardless of application area, project size, or complexity, software development work may be divided into three generic phases: the_____ phase, which focuses on what, the_____ phase, which focuses on how, and the_____ phase, which focuses on change.\n i. support\n ii. development\n iii. definition\n a) iii, ii, i\n b) iii, i, ii\n c) i, ii, iii\n d) ii, i, iii\n","a"],
    ["_____ software development team has no permanent leader.\n a) Controlled Centralized (CC)\n b) Controlled decentralized (CD)\n c) Democratic decentralized (DD)\n d) None of the mentioned\n","c"],
    ["Software patch is defined as _____\n a) Daily or routine Fix\n b) Required or Critical Fix\n c) Emergency Fix\n d) None of the mentioned\n","c"],
    ["_____ suits the Manifesto for Agile Software Development.\n a) Customer collaboration\n b) Individuals and interactions\n c) Working software\n d) All of the mentioned\n","d"],
    ["_____ is not among the eight principles followed by the Software Code of Ethics and Professional Practice.\n a) Product\n b) Environment\n c) Public\n d) Profession\n","b"],
    ["Who proposed the spiral model?\n a) Barry Boehm\n b) Pressman\n c) Royce\n d) IBM\n","a"],
    ["What does SDLC stands for?\n a) System Design Life Cycle\n b) Software Design Life Cycle\n c) Software Development Life Cycle\n d) System Development Life cycle\n","c"],
    ["The Cleanroom philosophy was proposed by _____\n a) Linger\n b) Mills\n c) Dyer\n d) All of the Mentioned\n","d"],
    ["Attributes of good software is _____\n a) Development\n b) Maintainability & functionality\n c) Functionality\n d) Maintainability\n","b"],
    ["Why do bugs and failures occur in software?\n a) Because of Developers\n b) Because of companies\n c) Because of both companies and Developers\n d) None of the mentioned\n","c"],
]
